spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/potato_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: password
  sql:
    init:
      mode: always
#      username: root
#      password: password
#      schema-locations: classpath:sql/init-schema.sql
#      data-locations: classpath:sql/init-data.sql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 设置在InterceptorConfig
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379
#  kafka:
#    bootstrap-servers: 43.138.129.57:9092 # 默认值
#    consumer:
#      group-id: group_test1
#    template:
#      default-topic: kafka_topic

#logging:
#  level:
#    com.example.potato_serve.mapper: debug

mybatis:
  # 未删除数据库保存的值，默认为0
  logic-not-delete-value: 0
  # 删除后数据库保存的值，默认为1
  logic-delete-value=: 1
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

knife4j:
  setting:
    enableDynamicParameter: true
